/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,ts}"],
  theme: {
    colors: {
      transparent: "transparent",
      "green-primary": "#C6D752",
      "green-secondary": "#D7E472",
      "green-ghost": "#E9F0A6",
      "black-primary": "#333333",
      "gray-primary": "#737373",
      "gray-secondary": "#D9D9D9",
      "gray-ghost": "#FAFAFA",
      white: "#FFFFFF",
      red: "#FF3939",
      "github-black": "#1A1A1A",
      "devto-black": "#333333",
      "twitter-blue": "#43B7E9",
      "codewars-red": "#8A1A50",
      "linkedin-blue": "#2D68FF",
      "freecodecamp-blue": "#302267",
      "youtube-red": "#EE3939",
      "gitlab-orange": "#EB4925",
      "facebook-blue": "2442AC",
      "hashnode-blue": "#0330D1",
      "twitch-pink": "#EE3FC8",
      "stackoverflow-orange": "#EC7100",
    },
    extend: {},
  },
  plugins: [],
};
