export const PLATFORMS = [
  {
    id: 1,
    name: 'GitHub',
    src: 'assets/svg/github.svg',
    previewSrc: 'assets/svg/github-preview.svg',
    color: 'github-black',
  },
  {
    id: 2,
    name: 'Dev.to',
    src: 'assets/svg/devto.svg',
    color: 'devto-black',
    previewSrc: 'assets/svg/devto-preview.svg',
  },
  {
    id: 3,
    name: 'Twitter',
    src: 'assets/svg/twitter.svg',
    color: 'twitter-blue',
    previewSrc: 'assets/svg/twitter-preview.svg',
  },
  {
    id: 4,
    name: 'Codewars',
    src: 'assets/svg/codewars.svg',
    color: 'codewars-red',
    previewSrc: 'assets/svg/codewars-preview.svg',
  },
  {
    id: 5,
    name: 'LinkedIn',
    src: 'assets/svg/linkedin.svg',
    color: 'linkedin-blue',
    previewSrc: 'assets/svg/linkedin-preview.svg',
  },
  {
    id: 6,
    name: 'freeCodeCamp',
    src: 'assets/svg/freecodecamp.svg',
    color: 'freecodecamp-blue',
    previewSrc: 'assets/svg/freecodecamp-preview.svg',
  },
  {
    id: 7,
    name: 'YouTube',
    src: 'assets/svg/youtube.svg',
    color: 'youtube-red',
    previewSrc: 'assets/svg/youtube-preview.svg',
  },
  {
    id: 8,
    name: 'GitLab',
    src: 'assets/svg/gitlab.svg',
    color: 'gitlab-orange',
    previewSrc: 'assets/svg/gitlab-preview.svg',
  },
  {
    id: 9,
    name: 'Facebook',
    src: 'assets/svg/facebook.svg',
    color: 'facebook-blue',
    previewSrc: 'assets/svg/facebook-preview.svg',
  },
  {
    id: 10,
    name: 'Hashnode',
    src: 'assets/svg/hashnode.svg',
    color: 'hashnode-blue',
    previewSrc: 'assets/svg/hashnode-preview.svg',
  },
  {
    id: 11,
    name: 'Twitch',
    src: 'assets/svg/twitch.svg',
    color: 'twitch-pink',
    previewSrc: 'assets/svg/twitch-preview.svg',
  },
  {
    id: 12,
    name: 'Stack Overflow',
    src: 'assets/svg/stack-overflow.svg',
    color: 'stackoverflow-orange',
    previewSrc: 'assets/svg/stack-overflow-preview.svg',
  },
];
